agent:
  - changed-files:
    - any-glob-to-any-file: pages/agent/**/*

cli:
  - changed-files:
    - any-glob-to-any-file: pages/cli/**/*

test-engine:
  - changed-files:
    - any-glob-to-any-file: pages/test_engine/**/*

pipelines:
  - changed-files:
    - any-glob-to-any-file:
      - pages/pipelines/**/*
      - pages/tutorials/**/*

plugins:
  - changed-files:
    - any-glob-to-any-file: pages/plugins/**/*

integrations:
  - changed-files:
    - any-glob-to-any-file: pages/integrations/**/*

api:
  - changed-files:
    - any-glob-to-any-file: pages/apis/**/*

graphql:
  - changed-files:
    - any-glob-to-any-file: pages/apis/graphql/**/*

rest:
  - changed-files:
    - any-glob-to-any-file: pages/apis/rest_api/**/*
