allow:
  - hooks
  - hook
  - execute
  - failure
  - failures
  - failed
  - period
  - periods
  - host-hostess
  - hostesses-hosts # Seems strange for these to be separate
  - color
  - colors
  - colored
  - special
  - execution
  - waiter
  - xxx
  - executes
  - executed
  - invalid
profanitySureness: 2
