parser: babel-eslint

extends:
  - eslint:recommended
  - plugin:import/react
  - plugin:import/recommended
  - plugin:react/recommended

globals:
  require: true
  Features: true
  process: true

env:
  es6: true
  browser: true

plugins:
  - import
  - react

ecmaFeatures:
  modules: true

rules:
  array-bracket-spacing:
    - error
    - never

  arrow-parens: warn
  arrow-spacing: warn

  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true

  comma-dangle:
    - error
    - never

  comma-spacing: error

  comma-style:
    - error
    - last

  curly:
    - error
    - all

  eqeqeq:
    - error
    - smart

  id-length: error

  indent:
    - error
    - 2
    - SwitchCase: 1
      MemberExpression: 1
      FunctionDeclaration:
        parameters: first
      FunctionExpression:
        parameters: first

  jsx-quotes: error
  key-spacing: error
  keyword-spacing: error
  linebreak-style: error
  no-console: warn
  no-const-assign: error
  no-duplicate-imports: error
  no-eval: error
  no-implied-eval: error
  no-new-require: error
  no-trailing-spaces: error
  no-unsafe-negation: error
  no-unused-vars: error
  no-useless-rename: warn
  no-var: warn

  object-curly-spacing:
    - error
    - always

  one-var:
    - error
    - initialized: never

  one-var-declaration-per-line: error
  prefer-const: warn
  radix: warn
  semi: error
  semi-spacing: error

  space-before-function-paren:
    - error
    - never

  space-in-parens:
    - error
    - never

  space-infix-ops: error
  space-unary-ops: error
  strict: error
  unicode-bom: error

  import/extensions: error
  import/unambiguous: off

  react/display-name:
    - error
    - ignoreTranspilerName: false

  react/forbid-prop-types: off

  react/jsx-boolean-value:
    - error
    - always

  react/jsx-closing-bracket-location: error
  react/jsx-curly-spacing: error

  react/jsx-equals-spacing:
    - error
    - never

  react/jsx-handler-names: error

  react/jsx-indent:
    - error
    - 2

  react/jsx-indent-props:
    - error
    - 2

  react/jsx-key: error
  react/jsx-max-props-per-line: off

  react/jsx-no-bind:
    - warn
    - ignoreRefs: true

  react/jsx-no-duplicate-props: error
  react/jsx-no-literals: off
  react/jsx-no-undef: error
  react/jsx-pascal-case: error
  react/jsx-sort-prop-types: off
  react/jsx-sort-props: off
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  react/jsx-wrap-multilines: error
  react/no-danger: off
  react/no-deprecated: error
  react/no-did-mount-set-state: error
  react/no-did-update-set-state: error
  react/no-direct-mutation-state: error
  react/no-is-mounted: error

  react/no-multi-comp:
    - error
    - ignoreStateless: true

  react/no-set-state: off
  react/no-string-refs: error
  react/no-unknown-property: error

  react/no-unused-prop-types:
    - error
    - skipShapeProps: true

  react/prefer-es6-class: error
  react/prefer-stateless-function: off
  react/prop-types: error
  react/react-in-jsx-scope: error
  react/self-closing-comp: warn
  react/sort-comp: off
  react/style-prop-object: warn
