steps:
  - label: Update GraphQL docs
    command: .buildkite/update_graphql_docs
    plugins:
      - docker-compose#v4.9.0:
          run: app
          mount-ssh-agent: true
          env:
            - GIT_NAME
            - GIT_EMAIL
            - GH_TOKEN
