steps:
  # NOTE: this input step is in the pipeline steps on Buildkite
  # - block: "Which PR needs to be synced?"
  #   fields:
  #     - key: pull_request_number
  #       required: true
  #       text: "Pull Request Number"
  #       format: "^[0-9]+$"
  #       hint: "Find the PR number on https://github.com/buildkite/docs/pulls"

  - label: ":git: Sync Public PR to Private Repo"
    command: "bin/sync-public-pr"
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-docs-private
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
      - aws-ssm#v1.0.0:
          parameters:
            GH_TOKEN: /pipelines/buildkite/docs-private/gh-token
      - docker#v5.11.0:
          image: "ruby:3.3-bookworm"
          propagate-environment: true
          mount-buildkite-agent: true
          environment:
            - GH_TOKEN
            - GH_PRIVATE_REPO
            - GH_PUBLIC_REPO
