steps:
  - name: ":docker::ecr: Push to ECR"
    command: ".buildkite/push-image.sh"
    depends_on: "rspec"
    key: "ecr-push"
    if: |
      build.branch == "main"
    agents:
      queue: deploy
    plugins:
     ecr#v2.0.0:
       login: true
       account-ids: ${ECR_ACCOUNT_ID}

  # If the current user is part of the deploy team, then wait for everything to
  # finish before deploying
  - wait: ~
    key: "deploy-check-wait"
    depends_on: "ecr-push"
    if: "(build.creator.teams includes 'deploy') && build.branch == 'main'"

  # If the user *isn't* in the deploy team, require a block step for manual
  # verification by someone who is in the team.
  - block: ":rocket: Deploy"
    key: "deploy-check-block"
    depends_on: "ecr-push"
    if: "!(build.creator.teams includes 'deploy') && build.branch == 'main'"

  - label: ":docker::rocket:"
    branches: main
    depends_on:
      - "deploy-check-wait"
      - "deploy-check-block"
    concurrency: 1
    concurrency_group: docs-deploy
    agents:
      queue: deploy
    command: scripts/deploy-ecs
