steps:
  - label: ":rspec: RSpec"
    command: bundle exec rspec
    artifact_paths: "log/rspec-*.xml"
    key: "rspec"
    env:
      RAILS_ENV: test
    plugins:
      - docker-compose#v3.0.0:
          run: app
          env:
            - BUILDKITE_JOB_ID
            - CI
            - RAILS_ENV

  - label: ":junit: Test Summary"
    depends_on: "rspec"
    allow_dependency_failure: true
    plugins:
      - bugcrowd/test-summary#v1.11.0:
          inputs:
            - label: ":rspec: RSpec"
              artifact_path: "log/rspec*"
              type: junit
          formatter:
            type: details
          context: test-summary

  - label: ":lint-roller: Linting"
    commands:
      - curl -sfL https://install.goreleaser.com/github.com/ValeLint/vale.sh | sh -s v2.9.1
      - ./bin/vale pages

  - label: ":lint-roller: Linting for insensitive words"
    command: npm run lint
    plugins:
      # Using the plain Node image, instead of the custom doc Dockerfile
      # version, is way faster because we don't have to wait for Ruby gems to
      # install.
      - docker#v3.7.0:
          # Alpine 3.12 - EOS 01-05-2022
          # lts = Node 1415.1 - 2023-04-30
          image: "node:14.18-alpine3.12"
