#!/bin/bash
set -euo pipefail

. bin/utils.sh

echo "+++ Fetch latest schema (via GraphQL introspection)"
docker compose run \
  --no-deps \
  -e API_ACCESS_TOKEN \
  app \
  bash -c "bundle exec rake graphql:fetch_schema >| data/graphql/schema.graphql"

echo "+++ Check for schema changes"
if git diff --exit-code --quiet data/graphql/schema.graphql; then
  buildkite-agent annotate  "Nothing to change, schema is up to date." --style "info"
  exit 0
fi

echo "+++ Schema changes detected..."
git --no-pager diff data/graphql/schema.graphql
git add data/graphql/schema.graphql

echo "-- Checking if existing pull request exists..."
BRANCH=buildkite-docs-bot/graphql/$(git rev-parse --short :data/graphql/schema.graphql)
PULL_REQUEST_NUMBER=$(get_branch_pull_request_number $BRANCH)

if [ -n "$PULL_REQUEST_NUMBER" ]; then
  buildkite-agent annotate "Nothing to change, pull request [#$PULL_REQUEST_NUMBER](https://github.com/buildkite/docs/pull/$PULL_REQUEST_NUMBER) awaiting approval." --style "info"
  exit 0
fi

echo "+++ Generate GraphQL docs"
docker compose run --no-deps app bundle exec rake graphql:generate

echo "--- Commit and push changes"
git add .
git config user.email $GIT_EMAIL
git config user.name $GIT_NAME
git checkout -b $BRANCH
git commit -m "Update GraphQL docs"

TARGET_REPO="https://dummy-user:${GH_TOKEN}@github.com/${GH_REPO}"
git push -f "${TARGET_REPO}" HEAD:${BRANCH}

echo "+++ Create pull request"
create_pull_request "Update GraphQL docs" "This is an automated PR based on the current GraphQL schema" "${BRANCH}" \
  | jq ".html_url" | buildkite-agent annotate --style "success"
