#!/bin/bash
set -euo pipefail

# echo "+++ Download GraphQL schema"
# buildkite-agent artifact download "schema.json" "docs/data/graphql_data_schema.json" --build $BUILDKITE_TRIGGERED_FROM_BUILD_ID

# if [[ -z "$(git status --porcelain)" ]]; then
#   echo "No changes to commit"
#   exit 0
# fi

echo "+++ Generate GraphQL docs"
./scripts/generate-graphql-api-content.sh

SCHEMA_HASH=$(git rev-parse --short :data/graphql_data_schema.json)

git config --global user.email $BUILDKITE_BUILD_AUTHOR_EMAIL
git config --global user.name $BUILDKITE_BUILD_AUTHOR

echo "+++ Commit and push changes"
git checkout -b graphql-schema-update-$SCHEMA_HASH
git add .
git commit -m "Update GraphQL docs" --allow-empty # fixme: this is temporary, until we have a schema change
# git commit -m "Update GraphQL docs"
git push -u origin graphql-schema-update-$SCHEMA_HASH

# echo "+++ Create pull request"
# gh pr create --title "Update GraphQL schema" --body "This PR updates the GraphQL schema to the latest version." --base master --head graphql-schema-update-$(date +%Y-%m-%d)

