<!--
  _____   ____    _   _  ____ _______   ______ _____ _____ _______ 
  |  __  / __   |  | |/ __ __   __| |  ____|  __ _   _|__   __|
  | |  | | |  | | |  | | |  | | | |    | |__  | |  | || |    | |   
  | |  | | |  | | | . ` | |  | | | |    |  __| | |  | || |    | |   
  | |__| | |__| | | |  | |__| | | |    | |____| |__| || |_   | |   
  |_____/ ____/  |_| _|____/  |_|    |______|_____/_____|  |_|   
  This file is auto-generated by script/generate_graphql_api_content.sh,
  please build the schema.json by running `rails api:graph:export`
  with https://github.com/buildkite/buildkite/,
  replace the content in data/graphql_data_schema.json
  and run the generation script `./scripts/generate-graphql-api-content.sh`.
-->
<!-- vale off -->
<h1 class="has-pills" data-algolia-exclude>
  NoticeNamespaces
  <span class="pill pill--enum pill--normal-case pill--large"><code>ENUM</code></span>
</h1>
<!-- vale on -->


<p>All the possible namespaces for a notice</p>


{:notoc}









<table class="responsive-table responsive-table--single-column-rows">
  <thead>
    <th>
      <h2 data-algolia-exclude>ENUM Values</h2>
    </th>
  </thead>
  <tbody>
    <tr><td><p><strong><code>CHANGE</code></strong></p><p>A change to an existing feature</p></td></tr><tr><td><p><strong><code>EMAIL_SUGGESTION</code></strong></p><p>The user has had an email suggested to them</p></td></tr><tr><td><p><strong><code>FEATURE</code></strong></p><p>A new feature was added</p></td></tr><tr><td><p><strong><code>EVENT</code></strong></p><p>An event announcement</p></td></tr>
  </tbody>
</table>
