#!/bin/bash
set -xeuo pipefail

export AWS_DEFAULT_REGION=us-east-1

cluster="buildkite-ecs"
task_family="docs"
service_name="docs"
image="${ECR_REPO}:${BUILDKITE_BUILD_NUMBER}"
executionRole="${ECS_EXECUTION_ROLE_ARN}"
http_host="https://buildkite.com/docs/"
templateFile="$(dirname $0)/../deploy/task-definition-template.json"
tmpfile="/tmp/task-definition.json"

echo "--- :ecs: Generating task definition JSON"
jq ".containerDefinitions[0].image = \"${image}\" | .executionRoleArn = \"${executionRole}\"" ${templateFile} > ${tmpfile}

echo "--- :ecs: Registering new task definition for ${task_family}"
task_revision=$(
  aws ecs register-task-definition --cli-input-json file://${tmpfile} | jq '.taskDefinition.revision'
)
echo "Registered ${task_family}:${task_revision}"

echo "--- :ecs: Updating service for ${service_name}"
aws ecs update-service \
  --cluster "${cluster}" \
  --service "${service_name}" \
  --task-definition "${task_family}:${task_revision}"

## Now we wait till it's stable
echo "--- :ecs: Waiting for services to stabilize"
aws ecs wait services-stable \
  --cluster "${cluster}" \
  --services "${service_name}"

aws ecs describe-services \
  --cluster "${cluster}" \
  --service "${service_name}"

echo "+++ :ecs: Service is up at ${http_host} 🚀"
