#!/bin/bash

# This script is used to migrate the docs from the old docs site to the new docs site.

# mv pages/* docusaurus-docs/docs

# rename all .md files to .mdx
# find . -type f -name "*.md" -exec rename "s/\.md/\.mdx/" '{}' \;

# remove {:toc} from all files
# find docusaurus-docs/docs -type f -name "*.mdx" -exec sed -i '' '/{:toc}/d' {} \;

# run eslint to fix formatting
cd docusaurus-docs
node_modules/.bin/eslint --fix docs
