#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Fetching latest agent version..."
AGENT_VERSION="$("${SCRIPT_DIR}/fetch-latest-agent-version.sh")"
echo "Using agent version: ${AGENT_VERSION}"

# Locally, things tend to get installed to $(go env GOBIN), but in CI, they get installed to $(go env GOPATH)/bin
# TIL these can be different!
INSTALL_PATH="$(go env GOBIN)"
if [[ -z $INSTALL_PATH ]]; then
  INSTALL_PATH="$(go env GOPATH)/bin"
fi

# Note that go install names the binary "agent", when it is normally
# "buildkite-agent". Rather than renaming, I'm leaving it, so that we avoid
# accidentally calling an existing buildkite-agent.
AGENT="${INSTALL_PATH}/agent"

echo "Installing buildkite-agent ${AGENT_VERSION} to ${AGENT}"

go install "github.com/buildkite/agent/v3@${AGENT_VERSION}"

echo "Installing agent_cli_discover"
go install -buildvcs=false ./scripts/agent_cli_discover
CLI_DISCOVER="${INSTALL_PATH}/agent_cli_discover"

echo "Installing agent_cli2md"
go install -buildvcs=false ./scripts/agent_cli2md
CLI2MD="${INSTALL_PATH}/agent_cli2md"

base_dir="$(git rev-parse --show-toplevel)"

# Discover commands, create scaffolding for new commands, update nav and overview.
# Full mode outputs leaf commands to stdout; stderr has status messages.
echo "Discovering commands from agent binary..."
commands=()
while IFS= read -r cmd; do
  commands+=("$cmd")
done < <("${CLI_DISCOVER}" "${AGENT}" "${base_dir}")

echo "Found ${#commands[@]} leaf commands"

for command in "${commands[@]}"; do
  file="${base_dir}/pages/agent/cli/help/_${command//[- ]/_}.md"

  echo "Updating docs for buildkite-agent ${command}"

  cat << 'EOF' >"${file}"
<!--

 _____           ______                _______    _ _
(____ \         |  ___ \       _      (_______)  | (_)_
 _   \ \ ___    | |   | | ___ | |_     _____   _ | |_| |_
| |   | / _ \   | |   | |/ _ \|  _)   |  ___) / || | |  _)
| |__/ / |_| |  | |   | | |_| | |__   | |____( (_| | | |__
|_____/ \___/   |_|   |_|\___/ \___)  |_______)____|_|\___)

This file is auto-generated by scripts/update-agent-help.sh.

Instead of directly changing this file, you must:

1. Update the agent CLI help content in https://github.com/buildkite/agent (not in this repo)
2. From the root of your docs repo, run ./scripts/update-agent-help.sh

-->

EOF

  # shellcheck disable=SC2086
  "${AGENT}" ${command} --help | "${CLI2MD}" >>"$file"
done
