#!/usr/bin/env bash

set -euo pipefail

scripts_dir=$(dirname "${BASH_SOURCE[0]}")
base_dir=$(git rev-parse --show-toplevel)
file="${base_dir}/data/content/agent_attributes.yaml"

cat << 'EOF' >"$file"
#   _____   ____    _   _  ____ _______   ______ _____ _____ _______
#  |  __ \ / __ \  | \ | |/ __ \__   __| |  ____|  __ \_   _|__   __|
#  | |  | | |  | | |  \| | |  | | | |    | |__  | |  | || |    | |
#  | |  | | |  | | | . ` | |  | | | |    |  __| | |  | || |    | |
#  | |__| | |__| | | |\  | |__| | | |    | |____| |__| || |_   | |
#  |_____/ \____/  |_| \_|\____/  |_|    |______|_____/_____|  |_|
#
# This file is auto-generated by scripts/update-agent-configuration.sh, please update the
# agent CLI help in https://github.com/buildkite/agent and run the generation
# script.
EOF

ruby "${scripts_dir}/parse-agent-attributes.rb" >>"$file"
