#!/usr/bin/env bash

set -euo pipefail

scripts_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
base_dir=$(git rev-parse --show-toplevel)
file="${base_dir}/data/content/agent_attributes.yaml"

INSTALL_PATH="$(go env GOBIN)"
if [[ -z $INSTALL_PATH ]]; then
  INSTALL_PATH="$(go env GOPATH)/bin"
fi

echo "Fetching latest agent version..."
AGENT_VERSION="$("${scripts_dir}/fetch-latest-agent-version.sh")"
echo "Using agent version: ${AGENT_VERSION}"

AGENT="${INSTALL_PATH}/agent"

echo "Installing buildkite-agent ${AGENT_VERSION} to ${INSTALL_PATH}"
go install "github.com/buildkite/agent/v3@${AGENT_VERSION}"

echo "Installing agent_attributes2yaml"
go install -buildvcs=false ./scripts/agent_attributes2yaml
AGENT2YAML="${INSTALL_PATH}/agent_attributes2yaml"

cat << 'EOF' >"$file"
#   _____   ____    _   _  ____ _______   ______ _____ _____ _______
#  |  __ \ / __ \  | \ | |/ __ \__   __| |  ____|  __ \_   _|__   __|
#  | |  | | |  | | |  \| | |  | | | |    | |__  | |  | || |    | |
#  | |  | | |  | | | . ` | |  | | | |    |  __| | |  | || |    | |
#  | |__| | |__| | | |\  | |__| | | |    | |____| |__| || |_   | |
#  |_____/ \____/  |_| \_|\____/  |_|    |______|_____/_____|  |_|
#
# This file is auto-generated by scripts/update-agent-configuration.sh, please update the
# agent CLI help in https://github.com/buildkite/agent and run the generation
# script.
EOF

"${AGENT}" start --help | "${AGENT2YAML}" >>"$file"
