#!/usr/bin/env ruby
# frozen_string_literal: true

# Script to generate supported agent versions documentation from GitHub releases
#
# This script fetches all releases from the buildkite/agent GitHub repository
# and generates a Markdown documentation page listing them in reverse
# chronological order, grouped by major and minor version.
#
# Usage:
#   ruby scripts/supported_agent_versions2md/supported_agent_versions2md.rb > pages/agent/v3/self_hosted/supported_versions.md
#
# Requirements:
#   - Ruby 3.0+
#   - Internet access to fetch from GitHub API

require 'json'
require 'open3'

GITHUB_API_URL = 'https://api.github.com/repos/buildkite/agent/releases'
MIN_MAJOR_VERSION = 3
MINOR_GROUP_SIZE = 10

def fetch_all_releases
  releases = []
  page = 1

  loop do
    url = "#{GITHUB_API_URL}?per_page=100&page=#{page}"
    stdout, stderr, status = Open3.capture3('curl', '-sS', '-f', url)
    raise "Failed to fetch #{url}: #{stderr}" unless status.success?

    page_releases = JSON.parse(stdout)
    break if page_releases.empty?

    releases.concat(page_releases)
    page += 1
  end

  releases
end

def parse_version(tag_name)
  match = tag_name.match(/^v(\d+)\.(\d+)/)
  return nil unless match

  { major: match[1].to_i, minor: match[2].to_i }
end

def filter_releases(releases)
  releases
    .reject { |r| r['draft'] }
    .reject { |r| r['tag_name'].match?(/beta/i) }
    .select { |r| parse_version(r['tag_name'])&.fetch(:major) == MIN_MAJOR_VERSION }
end

def group_releases(releases)
  releases
    .group_by { |r| parse_version(r['tag_name'])[:major] }
    .sort_by { |major, _| -major }
    .map do |major, major_releases|
      minor_groups = major_releases
        .group_by { |r| (parse_version(r['tag_name'])[:minor] / MINOR_GROUP_SIZE) * MINOR_GROUP_SIZE }
        .sort_by { |group, _| -group }
        .map do |group, group_releases|
          sorted = group_releases.sort_by { |r| r['published_at'] }.reverse
          { range_start: group, range_end: group + MINOR_GROUP_SIZE - 1, releases: sorted }
        end

      { major: major, groups: minor_groups }
    end
end

def format_date(published_at)
  published_at.split('T').first
end

def generate_markdown(version_groups)
  output = []

  output << '<!--'
  output << ' _____           ______                _______    _ _'
  output << '(____ \         |  ___ \       _      (_______)  | (_)_'
  output << ' _   \ \ ___    | |   | | ___ | |_     _____   _ | |_| |_'
  output << '| |   | / _ \   | |   | |/ _ \|  _)   |  ___) / || | |  _)'
  output << '| |__/ / |_| |  | |   | | |_| | |__   | |____( (_| | | |__'
  output << '|_____/ \___/   |_|   |_|\___/ \___)  |_______)____|_|\___)'
  output << ''
  output << 'This file is auto-generated by scripts/supported_agent_versions2md/supported_agent_versions2md.rb.'
  output << ''
  output << 'To update this file:'
  output << ''
  output << "1. Run './scripts/update-supported-agent-versions.sh' from the docs repo root"
  output << '-->'
  output << ''
  output << '# Supported agent versions'
  output << ''
  output << 'The following lists of Buildkite agent releases are ones that Buildkite currently supports, and are presented in reverse chronological order. Each version links through to its release notes on GitHub.'
  output << ''
  output << '> 📘 Unsupported agent versions'
  output << '> Earlier agent versions that are either beta releases or deprecated ones (version 2 releases and earlier), are not supported by Buildkite. Hence, these unsupported agent versions are not listed on this page, although their releases and release notes are still available from the [Buildkite Agent releases](https://github.com/buildkite/agent/releases) page on GitHub.'
  output << '> See [Upgrading agents from unsupported versions](/docs/agent/v3/self-hosted/supported-versions/upgrading-from-unsupported) for guidance on how to upgrade to the latest or a recent agent release.'
  output << ''

  version_groups.each do |group|
    group[:groups].each do |minor_group|
      output << "## Agent versions #{group[:major]}.#{minor_group[:range_start]} to #{group[:major]}.#{minor_group[:range_end]}"
      output << ''
      output << '<table>'
      output << '  <thead>'
      output << '    <tr>'
      output << '      <th>Agent version</th>'
      output << '      <th>Date of release</th>'
      output << '    </tr>'
      output << '  </thead>'
      output << '  <tbody>'
      output << '    <% ['

      minor_group[:releases].each_with_index do |release, i|
        tag = release['tag_name']
        date = format_date(release['published_at'])
        comma = i < minor_group[:releases].length - 1 ? ',' : ''
        output << '      {'
        output << "        version: \"#{tag}\","
        output << "        date: \"#{date}\""
        output << "      }#{comma}"
      end

      output << '    ].each do |release| %>'
      output << '      <tr>'
      output << '        <td><a href="https://github.com/buildkite/agent/releases/tag/<%= release[:version] %>"><code><%= release[:version] %></code></a></td>'
      output << '        <td><%= release[:date] %></td>'
      output << '      </tr>'
      output << '    <% end %>'
      output << '  </tbody>'
      output << '</table>'
      output << ''
    end
  end

  output << '## Upgrading from unsupported versions'
  output << ''
  output << "If you're running an [unsupported agent version](#unsupported-agent-versions), see [Upgrading agents from unsupported versions](/docs/agent/v3/self-hosted/supported-versions/upgrading-from-unsupported) for guidance on how to upgrade to the latest or a recent agent release."

  output.join("\n")
end

def main
  $stderr.puts 'Fetching all releases from github.com/buildkite/agent...'
  releases = fetch_all_releases

  $stderr.puts "Found #{releases.length} total releases"

  filtered = filter_releases(releases)
  $stderr.puts "Filtered to #{filtered.length} releases (v#{MIN_MAJOR_VERSION}+, non-beta, non-draft)"

  version_groups = group_releases(filtered)

  puts generate_markdown(version_groups)
end

main
