class ApplicationController < ActionController::Base
  def route_not_found
    render file: Rails.root.join("public","404.html"), layout: false, status: 404
  end

  private

  def default_nav
    Rails.application.config.default_nav
  end

  # capture some extra data so we can log it with lograge
  def append_info_to_payload(payload)
    super

    # Use the request ID generated by the aamzon ALB, if available
    payload[:request_id] = request.headers.fetch("X-Amzn-Trace-Id", request.request_id)
    payload[:remote_ip] = request.remote_ip
    payload[:user_agent] = request.user_agent
  end
end
