AgentInstallers = [
  { title: "Ubuntu",
    url: "agent/v3/self-hosted/installing/ubuntu" },
  { title: "Debian",
    url: "agent/v3/self-hosted/installing/debian" },
  { title: "Red Hat/CentOS",
    url: "agent/v3/self-hosted/installing/redhat" },
  { title: "FreeBSD",
    url: "agent/v3/self-hosted/installing/freebsd" },
  { title: "macOS",
    url: "agent/v3/self-hosted/installing/macos" },
  { title: "Windows",
    url: "agent/v3/self-hosted/installing/windows" },
  { title: "Linux",
    url: "agent/v3/self-hosted/installing/linux" },
  { title: "Docker",
    url: "agent/v3/self-hosted/installing/docker" },
  { title: "Agent Stack for Kubernetes",
    url: "agent/v3/self-hosted/agent-stack-k8s" },
  { title: "AWS",
    url: "agent/v3/self-hosted/aws" },
  { title: "Elastic CI Stack for AWS",
    url: "agent/v3/self-hosted/aws/elastic-ci-stack/ec2-linux-and-windows/setup" },
  { title: "Google Cloud",
    url: "agent/v3/self-hosted/gcp" }
].freeze
