AgentInstallers = [
  { title: "Ubuntu",
    url: "agent/v3/ubuntu" },
  { title: "Debian",
    url: "agent/v3/debian" },
  { title: "Red Hat/CentOS",
    url: "agent/v3/redhat" },
  { title: "FreeBSD",
    url: "agent/v3/freebsd" },
  { title: "macOS",
    url: "agent/v3/macos" },
  { title: "Windows",
    url: "agent/v3/windows" },
  { title: "Linux",
    url: "agent/v3/linux" },
  { title: "Docker",
    url: "agent/v3/docker" },
  { title: "AWS",
    url: "agent/v3/self-hosted/aws" },
  { title: "Elastic CI Stack for AWS",
    url: "agent/v3/self-hosted/aws/elastic-ci-stack/ec2-linux-and-windows/setup" },
  { title: "Google Cloud",
    url: "agent/v3/self-hosted/gcp" },
  { title: "Agent Stack for Kubernetes",
    url: "agent/v3/self-hosted/agent-stack-k8s" }
].freeze
