AgentInstallers = [
  { title: "Ubuntu",
    url: "agent/v3/self-hosted/install/ubuntu" },
  { title: "Debian",
    url: "agent/v3/self-hosted/install/debian" },
  { title: "Red Hat/CentOS",
    url: "agent/v3/self-hosted/install/redhat" },
  { title: "FreeBSD",
    url: "agent/v3/self-hosted/install/freebsd" },
  { title: "macOS",
    url: "agent/v3/self-hosted/install/macos" },
  { title: "Windows",
    url: "agent/v3/self-hosted/install/windows" },
  { title: "Linux",
    url: "agent/v3/self-hosted/install/linux" },
  { title: "Docker",
    url: "agent/v3/self-hosted/install/docker" },
  { title: "Agent Stack for Kubernetes",
    url: "agent/v3/self-hosted/agent-stack-k8s" },
  { title: "AWS",
    url: "agent/v3/self-hosted/aws" },
  { title: "Elastic CI Stack for AWS",
    url: "agent/v3/self-hosted/aws/elastic-ci-stack/ec2-linux-and-windows/setup" },
  { title: "Google Cloud",
    url: "agent/v3/self-hosted/gcp" }
].freeze
