#!/usr/bin/env ruby
# frozen_string_literal: true

# Script to generate supported agent versions documentation from GitHub releases
#
# This script fetches all releases from the buildkite/agent GitHub repository
# and generates a Markdown documentation page listing them in reverse
# chronological order, grouped by major and minor version.
#
# Usage:
#   ruby scripts/agent_versions_directory2md/agent_versions_directory2md.rb > pages/agent/v3/self_hosted/versions_directory.md
#
# Requirements:
#   - Ruby 3.0+
#   - Internet access to fetch from GitHub API

require 'json'
require 'open3'

GITHUB_API_URL = 'https://api.github.com/repos/buildkite/agent/releases'
MIN_MAJOR_VERSION = 3
MINOR_GROUP_SIZE = 10

VERSIONS_WITH_KNOWN_ISSUES = %w[
  3.8.0
  3.8.1
  3.8.2
  3.8.3
  3.11.0
  3.11.3
  3.11.4
  3.13.1
  3.18.0
  3.43.0
  3.50.0
  3.50.1
  3.76.0
  3.76.1
  3.76.2
  3.77.0
  3.78.0
  3.79.0
  3.80.0
  3.81.0
  3.82.0
  3.112.0
].freeze

def fetch_all_releases
  releases = []
  page = 1

  loop do
    url = "#{GITHUB_API_URL}?per_page=100&page=#{page}"
    stdout, stderr, status = Open3.capture3('curl', '-sS', '-f', url)
    raise "Failed to fetch #{url}: #{stderr}" unless status.success?

    page_releases = JSON.parse(stdout)
    break if page_releases.empty?

    releases.concat(page_releases)
    page += 1
  end

  releases
end

def parse_version(tag_name)
  match = tag_name.match(/^v(\d+)\.(\d+)/)
  return nil unless match

  { major: match[1].to_i, minor: match[2].to_i }
end

def filter_releases(releases)
  releases
    .reject { |r| r['draft'] }
    .reject { |r| r['tag_name'].match?(/beta/i) }
    .select { |r| parse_version(r['tag_name'])&.fetch(:major) == MIN_MAJOR_VERSION }
end

def group_releases(releases)
  releases
    .group_by { |r| parse_version(r['tag_name'])[:major] }
    .sort_by { |major, _| -major }
    .map do |major, major_releases|
      minor_groups = major_releases
        .group_by { |r| (parse_version(r['tag_name'])[:minor] / MINOR_GROUP_SIZE) * MINOR_GROUP_SIZE }
        .sort_by { |group, _| -group }
        .map do |group, group_releases|
          sorted = group_releases.sort_by { |r| r['published_at'] }.reverse
          { range_start: group, range_end: group + MINOR_GROUP_SIZE - 1, releases: sorted }
        end

      { major: major, groups: minor_groups }
    end
end

def format_date(published_at)
  published_at.split('T').first
end

def known_issues?(tag_name)
  version = tag_name.sub(/^v/, '')
  VERSIONS_WITH_KNOWN_ISSUES.include?(version)
end

def generate_release_table(output, releases)
  has_any_known_issues = releases.any? { |r| known_issues?(r['tag_name']) }

  output << '<table>'
  output << '  <thead>'
  output << '    <tr>'
  output << '      <th>Release changelog</th>'
  output << '      <th style="text-align: center">Date of release</th>'
  output << '      <th style="text-align: center">Known issues</th>' if has_any_known_issues
  output << '    </tr>'
  output << '  </thead>'
  output << '  <tbody>'
  output << '    <% ['

  releases.each_with_index do |release, i|
    tag = release['tag_name']
    date = format_date(release['published_at'])
    comma = i < releases.length - 1 ? ',' : ''
    output << '      {'
    output << "        version: \"#{tag}\","
    if has_any_known_issues
      output << "        date: \"#{date}\","
      output << "        known_issues: #{known_issues?(tag)}"
    else
      output << "        date: \"#{date}\""
    end
    output << "      }#{comma}"
  end

  output << '    ].each do |release| %>'
  output << '      <tr>'
  output << '        <td><a href="https://github.com/buildkite/agent/releases/tag/<%= release[:version] %>"><code><%= release[:version] %></code></a></td>'
  output << '        <td style="text-align: center"><%= release[:date] %></td>'
  if has_any_known_issues
    output << '        <td style="text-align: center"><%= release[:known_issues] ? "Known issues, see <a href=\"https://github.com/buildkite/agent/releases/tag/#{release[:version]}\">changelog</a> for details." : "" %></td>'
  end
  output << '      </tr>'
  output << '    <% end %>'
  output << '  </tbody>'
  output << '</table>'
end

def generate_markdown(version_groups)
  output = []

  output << '<!--'
  output << ' _____           ______                _______    _ _'
  output << '(____ \         |  ___ \       _      (_______)  | (_)_'
  output << ' _   \ \ ___    | |   | | ___ | |_     _____   _ | |_| |_'
  output << '| |   | / _ \   | |   | |/ _ \|  _)   |  ___) / || | |  _)'
  output << '| |__/ / |_| |  | |   | | |_| | |__   | |____( (_| | | |__'
  output << '|_____/ \___/   |_|   |_|\___/ \___)  |_______)____|_|\___)'
  output << ''
  output << 'This file is auto-generated by scripts/agent_versions_directory2md/agent_versions_directory2md.rb.'
  output << ''
  output << 'To update this file:'
  output << ''
  output << "1. Run './scripts/update-agent-versions-directory.sh' from the docs repo root"
  output << '-->'
  output << ''
  output << '# Agent versions directory'
  output << ''
  output << 'The following lists of Buildkite agent versions are of stable version 3.x releases in reverse chronological order. Each version links through to its changelog on GitHub.'
  output << ''
  output << 'Agent versions with known issues are indicated in these tables.'
  output << ''

  version_groups.each do |group|
    group[:groups].each do |minor_group|
      output << "## Agent versions #{group[:major]}.#{minor_group[:range_start]} to #{group[:major]}.#{minor_group[:range_end]}"
      output << ''
      generate_release_table(output, minor_group[:releases])
      output << ''
    end
  end

  output << '## Agent versions 2.x'
  output << ''
  output << "Buildkite version 2.x agent releases are not listed on this page. However, their installer bundles and changelogs are still available from the [Buildkite Agent releases](https://github.com/buildkite/agent/releases) page."
  output << ''
  output << "To upgrade from a 3.0-beta or 2.x agent version to a stable 3.x one, see [Upgrading from 3.0-beta and 2.x versions](/docs/agent/v3/self-hosted/versions-directory/upgrading-from-3-dot-0-beta-and-v2)."

  output.join("\n")
end

def main
  $stderr.puts 'Fetching all releases from github.com/buildkite/agent...'
  releases = fetch_all_releases

  $stderr.puts "Found #{releases.length} total releases"

  filtered = filter_releases(releases)
  $stderr.puts "Filtered to #{filtered.length} releases (v#{MIN_MAJOR_VERSION}+, non-beta, non-draft)"

  version_groups = group_releases(filtered)

  puts generate_markdown(version_groups)
end

main
